language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules #Cache node_modules for faster builds
script:
  - npm run build #Creats a production build
env:
  - NODE_ENV=dev
  - PUBLIC_URL=https://georgieff.github.io/twitter-backup/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
