export const LOAD_TWEETS = 'LOAD_TWEETS';
export const LOAD_SAVED_TWEETS = 'LOAD_SAVED_TWEETS';
export const CLEAR_TWEETS = 'CLEAR_TWEETS';

export const ADD_SAVED_TWEET = 'ADD_SAVED_TWEETS';
export const REMOVE_SAVED_TWEET = 'REMOVE_SAVED_TWEETS';
export const CLEAR_SAVED_TWEETS = 'CLEAR_SAVED_TWEETS';

export const LOAD_USER = 'LOAD_USER';
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
